name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        IMAGE_REPO=345594584716.dkr.ecr.ca-central-1.amazonaws.com/ass3/uma-ecr
        docker build -t $IMAGE_REPO:$IMAGE_TAG -t $IMAGE_REPO:latest .
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Push image to ECR
      run: |
        IMAGE_REPO=345594584716.dkr.ecr.ca-central-1.amazonaws.com/ass3/uma-ecr
        docker push $IMAGE_REPO:$IMAGE_TAG
        docker push $IMAGE_REPO:latest
